<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="union_server.aspx.cs" Inherits="massive_code.union_server" %>
<%@ Register assembly="DevExpress.Web.v15.1, Version=15.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" namespace="DevExpress.Web" tagprefix="dx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style59 {
        color: #006699;
    }
        .auto-style60 {
            color: #009933;
        }

        .auto-style70 {
            width: 255px;
        }
        .auto-style71 {
            width: 94px;
        }
        .auto-style72 {
            width: 104px;
        }
        .auto-style73 {
            width: 28px;
        }

    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table style="width: 100%;">
        <tr>
            <td colspan="2" rowspan="3">&nbsp;</td>
            <td class="auto-style73">&nbsp;</td>
            <td class="auto-style70">&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style73">&nbsp;</td>
            <td class="auto-style70">
                <asp:Button ID="Button_Download_UnionServer" runat="server" Font-Names="Times New Roman" Height="42px" style="font-size: large; text-align: center;" OnClick="Button_Download_UnionServer_Click" Text="DOWNLOAD" Width="244px" CssClass="button_union_download_stat" />
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style73"></td>
            <td class="auto-style70">
            <asp:Button ID="Button_GIT_Click" runat="server" CssClass="button_github_stat" Font-Names="Times New Roman" Height="42px" OnClick="Button_GIT_Click_Click" style="font-size: large; text-align: center;" Text="UNION SERVER GITHIB" Width="243px" />
            </td>
            <td></td>
        </tr>
        <tr>
            <td class="auto-style71">&nbsp;</td>
            <td class="auto-style72" rowspan="2">
                <dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server" BackColor="White" EnableTheming="True" Height="367px" ImageSourceFolder="~/images/server/" Theme="DevEx" Width="513px">
                     <SettingsNavigationBar Mode="Dots" />
                <SettingsAutoGeneratedImages ImageCacheFolder="~\Thumb\" />
                <Styles>
                    <ImageArea BackColor="White">
                    </ImageArea>
                </Styles>
                <Border BorderStyle="None" BorderWidth="1px" />
                </dx:ASPxImageSlider>
            </td>
            <td class="auto-style73">&nbsp;</td>
            <td class="auto-style70"><span class="auto-style60">Основная часть клиент-серверной системы корпоративного общения между сотрудниками</span><br class="auto-style60" />
                <span class="auto-style60">Воспользуйтесь бесплатной версией программы с открытым исходным кодом. Пройдите вместе со мной все этапы разработки программного продукта. Вместе мы рассмотрим каким образом работают системы социального общения от баз данных до работы в сети.</span></td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style71">&nbsp;</td>
            <td class="auto-style73">&nbsp;</td>
            <td class="auto-style70"><span  class="auto-style59"><strong >Системные требования: Windows 7 Windows 2008 Server и выше</strong></span><strong><br class="auto-style59" />
                </strong><span  class="auto-style59"><strong >NET Framework 4.5
                <br />
                SQL Compact Edition 4.0</strong></span><strong ><br  class="auto-style59" />
                </strong><span class="auto-style59"><strong >Подключение к локальной сети либо к сети Интернет</strong></span></td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
            <td class="auto-style73">&nbsp;</td>
            <td class="auto-style70">&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </table>
</asp:Content>
